### ISSUE TITLE
Android 13 + Flutter 3: Inter bold weight rounded glyphs issue

### ISSUE THREAD

**Issue by lucien144** [material-foundation/flutter-packages#258]
## Steps to Reproduce

Use Inter font in your CupertinoTextThemeData and run it under Android 13 with Flutter 3. 

1. If you change the font to other GoogleFonts, the problem no longer appears - indicating this is just the Inter font issue. 
1. Similarly, if you run the same code in iOS - the problem does not exist here, indicating it's Android related.
1. Tested on Android 11 and it also works -> indicating it's Android 13 related.

I'm sorry if this should be reported to Inter's Github repo...

**Expected results:**
![IMG_7756 2](https://user-images.githubusercontent.com/5161085/186185618-95df759f-45ae-43e4-b5ce-f3075e93c4e1.jpg)

**Actual results:** 
![](https://user-images.githubusercontent.com/4223239/186015136-1b68dd0c-c4c4-4fd1-ad1a-6af94b6a3d55.png)

<details>
<summary>Code sample</summary>

```dart
... 
    textTheme: CupertinoTextThemeData(textStyle: GoogleFonts.inter(color: lightColors.text, fontSize: fontSize),
...
```

</details>

<details>
  <summary>Logs</summary>

```
$ flutter doctor -v

[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.1 20G224 darwin-x64, locale en-AU)
    • Flutter version 3.0.5 at /Applications/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/<USER>/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Users/<USER>/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/<USER>/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/<USER>/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Users/<USER>/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3739.24

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
    • IntelliJ at /Users/<USER>/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3739.54/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Users/<USER>/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.5744.223/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by nWacky** [comment]
I'm having the same issue with [Exo 2](https://fonts.google.com/specimen/Exo+2) on Xiaomi Android 10

What helped me was to import the font via `fonts` in pubspec.yaml

**Comment by guidezpl** [comment]
Is this still reproducible? Which version of `google_fonts` are you using?

**Comment by nWacky** [comment]
I think so. I have downloaded it from google fonts yesterday.

Did you overwrite `fontWeight` and `fontFamily` manually inside `Text`?

```dart
Text(
  'You have pushed the button this many times:',
  style: Theme.of(context).textTheme.headlineSmall!.copyWith(
      fontWeight: FontWeight.w600,
      fontFamily: GoogleFonts.exo2().fontFamily),
  textAlign: TextAlign.center,
)
```

**Comment by guidezpl** [comment]
Yeah the code sample was exactly copied. The specifying of additional folder wouldn't have any effect. I suggest you try to debug by attempting to repro the way I did, using the example. That might help clarify where the issue lies.

**Comment by augb** [comment]
@guidezpl I am having a similar problem on Flutter 3.3.9 for web using Montserrat:

<img width="596" alt="Screen Shot 2022-12-10 at 2 05 23 PM" src="https://user-images.githubusercontent.com/841357/206873372-385386c8-f632-4c69-8906-5d8e0bf82dfa.png">

I have modified the example project from the [gist](https://gist.github.com/nWacky/551656dad873ac1e219be6abc5cfbd57) provided by @nWacky as so:

main.dart

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  GoogleFonts.config.allowRuntimeFetching = false;

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final baseTheme = ThemeData(primaryColor: Colors.blue);

    return MaterialApp(
      title: 'Flutter Demo',
      theme: baseTheme,
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
              style: Theme.of(context).textTheme.headlineSmall!.copyWith(
                  fontWeight: FontWeight.w600,
                  fontFamily: GoogleFonts.montserrat().fontFamily),
              textAlign: TextAlign.center,
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

My `pubspec.yaml` looks like this:

```yaml
name: test_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - google_fonts/
    - google_fonts/Montserrat/
    - google_fonts/Montserrat/static/
  fonts:
    - family: Montserrat
      fonts:
        - asset: google_fonts/Montserrat/static/Montserrat-Thin.ttf
          weight: 100
        - asset: google_fonts/Montserrat/static/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: google_fonts/Montserrat/static/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: google_fonts/Montserrat/static/Montserrat-Light.ttf
          weight: 300
        - asset: google_fonts/Montserrat/static/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: google_fonts/Montserrat/static/Montserrat-Regular.ttf
          weight: 400
        - asset: google_fonts/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: google_fonts/Montserrat/static/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: google_fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: google_fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: google_fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
        - asset: google_fonts/Montserrat/static/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/Montserrat/static/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: google_fonts/Montserrat/static/Montserrat-Black.ttf
          weight: 900
        - asset: google_fonts/Montserrat/static/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

With the font files in the appropriate place in the project:

<img width="670" alt="Screen Shot 2022-12-10 at 2 11 12 PM" src="https://user-images.githubusercontent.com/841357/206873570-b650a02d-74d8-4b93-bb2a-f44c03162662.png">

`flutter doctor`:

<img width="622" alt="Screen Shot 2022-12-10 at 2 12 58 PM" src="https://user-images.githubusercontent.com/841357/206873641-002280d1-02f3-4ea7-8bb6-b2daa97be5bc.png">
